import React, { useState } from 'react';
import {
  Sparkles,
  Calendar,
  AlertTriangle,
  CheckCircle2,
  Copy,
  Share2,
  Printer,
  ChevronRight,
  ExternalLink,
  Shield,
  Layers,
  ArrowUpRight,
} from 'lucide-react';
import { DailyDigest, NotificationItem } from '../types';
import { getRegulatorStyle, getUrgencyBadge } from '../utils/theme';

interface DailyDigestViewProps {
  digest: DailyDigest | null;
  loading: boolean;
  onOpenNotification: (item: NotificationItem) => void;
}

export const DailyDigestView: React.FC<DailyDigestViewProps> = ({
  digest,
  loading,
  onOpenNotification,
}) => {
  const [copiedMemo, setCopiedMemo] = useState(false);

  if (loading) {
    return (
      <div className="rounded-xl border border-slate-200 bg-white p-12 text-center shadow-xs">
        <div className="inline-flex h-8 w-8 animate-spin rounded-full border-2 border-blue-600 border-t-transparent mb-3" />
        <p className="font-mono text-sm text-slate-700">Compiling today's executive regulatory digest...</p>
      </div>
    );
  }

  if (!digest) {
    return (
      <div className="rounded-xl border border-slate-200 bg-white p-10 text-center shadow-xs">
        <p className="text-sm text-slate-500">No daily digest available at this time.</p>
      </div>
    );
  }

  const formattedDate = new Date().toLocaleDateString('en-IN', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const handleCopyMemo = () => {
    const text = `REGINTEL DAILY COMPLIANCE BRIEFING — ${formattedDate}
------------------------------------------------------------
SUMMARY:
${digest.executiveBrief}

KEY ACTION ITEMS FOR COMPLIANCE COMMITTEE:
${digest.topActionItems.map((a, i) => `${i + 1}. ${a}`).join('\n')}

CIRCULARS OVERVIEW (${digest.totalNotifications} updates):
${digest.items
  .map(
    (item) =>
      `• [${item.regulator}] ${item.title}\n  Ref: ${item.refNumber || 'N/A'}\n  AI Brief: ${item.aiSummary}\n  Link: ${item.sourceUrl}\n`
  )
  .join('\n')}
------------------------------------------------------------
Generated by RegIntel Feed (Google AI Studio)`;

    navigator.clipboard.writeText(text);
    setCopiedMemo(true);
    setTimeout(() => setCopiedMemo(false), 2500);
  };

  return (
    <div className="space-y-5">
      {/* Digest Executive Header */}
      <div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="flex h-6 w-6 items-center justify-center rounded bg-amber-50 text-amber-700 border border-amber-200">
                <Sparkles className="h-3.5 w-3.5" />
              </span>
              <h2 className="font-sans text-base sm:text-lg font-bold text-slate-900 tracking-tight">
                Daily Morning Compliance Briefing
              </h2>
            </div>
            <p className="flex items-center gap-1.5 text-xs text-slate-500 font-mono">
              <Calendar className="h-3.5 w-3.5 text-slate-400" />
              <span>{formattedDate}</span>
              <span>• Curated for Senior CAs, RIAs & Compliance Heads</span>
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="copy-digest-memo-btn"
              onClick={handleCopyMemo}
              className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-3.5 py-2 text-xs font-semibold text-white hover:bg-blue-700 transition-all shadow-xs"
            >
              {copiedMemo ? (
                <>
                  <CheckCircle2 className="h-3.5 w-3.5 text-white" />
                  <span>Memo Copied to Clipboard!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span>Copy Morning Memo</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Top Metric Strip */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 pt-4">
          <div className="rounded-lg border border-slate-200 bg-slate-50/70 p-3">
            <span className="text-[11px] font-mono text-slate-500 block mb-0.5">Total Updates</span>
            <span className="font-mono text-xl font-bold text-slate-900">{digest.totalNotifications}</span>
          </div>

          <div className="rounded-lg border border-rose-200 bg-rose-50/60 p-3">
            <span className="text-[11px] font-mono text-rose-700 block mb-0.5 font-semibold">High Urgency Alerts</span>
            <span className="font-mono text-xl font-bold text-rose-700">{digest.highUrgencyCount}</span>
          </div>

          <div className="rounded-lg border border-slate-200 bg-slate-50/70 p-3 col-span-2">
            <span className="text-[11px] font-mono text-slate-500 block mb-1">Regulator Perimeter</span>
            <div className="flex flex-wrap items-center gap-1.5">
              {Object.entries(digest.regulatorBreakdown).map(([reg, count]) => {
                const style = getRegulatorStyle(reg as any);
                return (
                  <span
                    key={reg}
                    className={`rounded px-1.5 py-0.5 text-[10px] font-mono font-semibold border ${style.bg} ${style.text} ${style.border}`}
                  >
                    {reg}: {count}
                  </span>
                );
              })}
            </div>
          </div>
        </div>

        {/* AI Executive Synthesis */}
        <div className="mt-4 rounded-lg border border-blue-200 bg-blue-50/50 p-4 text-xs leading-relaxed text-slate-800">
          <div className="flex items-center gap-1.5 font-mono text-[11px] font-bold text-blue-700 uppercase tracking-wider mb-1.5">
            <Sparkles className="h-3.5 w-3.5" />
            <span>AI Executive Synthesis</span>
          </div>
          <p className="font-sans text-slate-800 text-sm leading-relaxed">{digest.executiveBrief}</p>
        </div>
      </div>

      {/* High-Priority Action Items */}
      {digest.topActionItems && digest.topActionItems.length > 0 && (
        <div className="rounded-xl border border-amber-200 bg-white p-5 shadow-xs">
          <div className="flex items-center gap-2 mb-3 font-mono text-xs font-bold text-amber-800 uppercase tracking-wider">
            <AlertTriangle className="h-4 w-4 text-amber-600" />
            <span>Top Compliance Action Items for Today</span>
          </div>
          <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
            {digest.topActionItems.map((action, i) => (
              <div
                key={i}
                className="flex items-start gap-2.5 rounded-lg border border-amber-200 bg-amber-50/60 p-3 text-xs text-amber-900 font-sans"
              >
                <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-amber-200 text-amber-900 font-mono text-[10px] font-bold mt-0.5">
                  {i + 1}
                </div>
                <p className="leading-snug">{action}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Fast Scannable Digest Items List */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-slate-600">
            Consolidated Circulars ({digest.items.length})
          </h3>
          <span className="text-[11px] font-mono text-slate-500">Sorted by Regulatory Importance</span>
        </div>

        <div className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white overflow-hidden shadow-xs">
          {digest.items.map((item) => {
            const regStyle = getRegulatorStyle(item.regulator);
            const urgency = getUrgencyBadge(item.urgency);

            return (
              <div
                key={item.id}
                className="p-4 sm:p-5 hover:bg-slate-50 transition-colors group"
              >
                <div className="flex flex-wrap items-center justify-between gap-2 mb-2">
                  <div className="flex items-center gap-2">
                    <span
                      className={`inline-flex items-center rounded px-2 py-0.5 text-xs font-mono font-bold uppercase border ${regStyle.bg} ${regStyle.text} ${regStyle.border}`}
                    >
                      {item.regulator}
                    </span>
                    <span className="font-mono text-[11px] text-slate-500 truncate max-w-xs">
                      {item.refNumber || 'Official Circular'}
                    </span>
                    <span
                      className={`rounded px-1.5 py-0.2 font-mono text-[10px] font-semibold uppercase ${urgency.bg}`}
                    >
                      {urgency.label}
                    </span>
                  </div>

                  <a
                    href={item.sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1 text-xs font-mono text-blue-600 hover:text-blue-800 hover:underline"
                  >
                    <span>Source</span>
                    <ArrowUpRight className="h-3 w-3" />
                  </a>
                </div>

                <h4 className="text-sm font-semibold text-slate-900 mb-1.5 leading-snug">
                  {item.title}
                </h4>

                <p className="text-xs text-slate-700 leading-relaxed mb-2.5 font-sans">
                  {item.aiSummary}
                </p>

                {/* Key Action Bullet Points */}
                {item.keyActionItems && item.keyActionItems.length > 0 && (
                  <div className="rounded-md border border-slate-200 bg-slate-50 p-2.5 text-xs text-slate-800">
                    <span className="font-mono text-[10px] font-bold uppercase text-amber-800 block mb-1">
                      Action Checklist:
                    </span>
                    <ul className="space-y-1">
                      {item.keyActionItems.map((act, idx) => (
                        <li key={idx} className="flex items-start gap-1.5 text-slate-700">
                          <CheckCircle2 className="h-3 w-3 text-emerald-600 mt-0.5 shrink-0" />
                          <span>{act}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
